// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bygtdsxawgpjvcvdtaya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5Z3Rkc3hhd2dwanZjdmR0YXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTUzNzYsImV4cCI6MjA2NDA5MTM3Nn0.6CtJFShEqu_5gHY9VMv6f7PlK7dt2wYR2KctYSjZupw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);